# Generated by Django 4.2.1 on 2023-05-23 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_articles_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='variable',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(100, 'full_text')]),
        ),
    ]
