# Generated by Django 4.2.1 on 2023-05-25 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_articles_variable_alter_articles_full_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(verbose_name='ФИО')),
                ('full_text', models.TextField(validators=[django.core.validators.MinLengthValidator(100, 'Введите больше 100 символов')], verbose_name='Приветственная речь')),
            ],
            options={
                'verbose_name': 'Директор',
                'verbose_name_plural': 'Директор',
            },
        ),
    ]
