# Generated by Django 4.2.1 on 2023-05-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='full_name',
            field=models.CharField(max_length=70, verbose_name='ФИО'),
        ),
    ]
