# Generated by Django 4.2.1 on 2023-05-25 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_director_image_alter_director_full_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_language', models.CharField(max_length=30, verbose_name='Язык')),
                ('full_text', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Введите больше 10 символов')], verbose_name='Описание кружка')),
                ('image', models.ImageField(default='', upload_to='images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Иностранный язык',
                'verbose_name_plural': 'Иностранные языки',
            },
        ),
    ]
