# Generated by Django 4.2.1 on 2023-05-25 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='english',
            name='disc_text',
            field=models.TextField(default='', validators=[django.core.validators.MinLengthValidator(10, 'Введите больше 10 символов')], verbose_name='Доп.описание'),
        ),
    ]
