# Generated by Django 4.2.1 on 2023-05-26 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_clubs_delete_chess_delete_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForParents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('full_text', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Введите больше 10 символов')], verbose_name='Описание')),
                ('disc_text', models.TextField(default='', validators=[django.core.validators.MinLengthValidator(10, 'Введите больше 10 символов')], verbose_name='Доп.описание')),
                ('image', models.ImageField(default='', upload_to='images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Для родителей',
                'verbose_name_plural': 'Для родителей',
            },
        ),
    ]
