# Generated by Django 4.2.1 on 2023-05-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_forparents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forparents',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
