# Generated by Django 4.2.1 on 2023-05-27 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_forparents_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(max_length=90, verbose_name='Приветствие')),
                ('full_text', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Введите больше 10 символов')], verbose_name='Описание')),
                ('disc_text', models.TextField(blank=True, default='', validators=[django.core.validators.MinLengthValidator(10, 'Введите больше 10 символов')], verbose_name='Доп.описание')),
                ('image', models.ImageField(default='', upload_to='images/', verbose_name='Изображение')),
            ],
        ),
        migrations.AlterField(
            model_name='forparents',
            name='disc_text',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MinLengthValidator(10, 'Введите больше 10 символов')], verbose_name='Доп.описание'),
        ),
    ]
