# Generated by Django 4.2.1 on 2023-06-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_about_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forparents',
            name='disc_text',
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название'),
        ),
    ]
