# Generated by Django 4.2.1 on 2023-06-04 10:13

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_about_full_text_alter_articles_full_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(validators=[django.core.validators.MinLengthValidator(10, 'Введите больше 10 символов')], verbose_name='Статья'),
        ),
    ]
