# Generated by Django 4.2.1 on 2023-06-04 12:11

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_about_image_alter_about_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='full_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(validators=[django.core.validators.MinLengthValidator(10, 'Введите больше 10 символов')], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='full_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(validators=[django.core.validators.MinLengthValidator(10, 'Введите больше 10 символов')], verbose_name='Описание кружка'),
        ),
        migrations.AlterField(
            model_name='director',
            name='full_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(validators=[django.core.validators.MinLengthValidator(10, 'Введите больше 10 символов')], verbose_name='Приветственная речь'),
        ),
        migrations.AlterField(
            model_name='forparents',
            name='full_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(validators=[django.core.validators.MinLengthValidator(10, 'Введите больше 10 символов')], verbose_name='Описание'),
        ),
    ]
