# Generated by Django 4.2.1 on 2023-06-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_about_full_text_alter_clubs_full_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
    ]
